{
 "title": "GWS Dash",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "GWS",
    "query": "{\"find\":\"terms\", \"field\":\"prometheus.labels.gws_name\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "3",
       "query": "*",
       "settings": {
        "filters": [
         {
          "label": "Provision",
          "query": "prometheus.labels.gws_name: \"$GWS\""
         }
        ]
       },
       "type": "filters"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "prometheus.metrics.storage_gws_provision",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "3",
       "query": "*",
       "settings": {
        "filters": [
         {
          "label": "Used",
          "query": "prometheus.labels.gws_name: \"$GWS\""
         }
        ]
       },
       "type": "filters"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "prometheus.metrics.storage_gws_used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Tape Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "3",
       "query": "*",
       "settings": {
        "filters": [
         {
          "label": "Quota",
          "query": "prometheus.labels.gws_name: \"$GWS\""
         }
        ]
       },
       "type": "filters"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "prometheus.metrics.tape_gws_quota",
       "id": "1",
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "3",
       "query": "*",
       "settings": {
        "filters": [
         {
          "label": "Used",
          "query": "prometheus.labels.gws_name: \"$GWS\""
         }
        ]
       },
       "type": "filters"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "prometheus.metrics.tape_gws_used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Number of users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$GWS Users",
     "bucketAggs": [
      {
       "fake": true,
       "id": "3",
       "query": "*",
       "settings": {
        "filters": [
         {
          "query": "prometheus.labels.gws_name: \"$GWS\""
         }
        ]
       },
       "type": "filters"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "prometheus.metrics.users_gws_active_today",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}