{
 "title": "Storage Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Overall Storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "dectbytes" }
   ],
   "targets": [
    {
     "alias": "Total",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "2h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "prometheus.metrics.storage_total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Committed",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "2h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "prometheus.metrics.storage_com",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GWS and archive prov & use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "alias": "GWS Provision",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "prometheus.metrics.storage_gws_provision",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "GWS Use",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "prometheus.metrics.storage_gws_used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Archive Provision",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "prometheus.metrics.storage_total_archive_provision",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Archive Usage",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "prometheus.metrics.storage_total_archive_used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SOF usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "dectbytes" }
   ],
   "targets": [
    {
     "alias": "Total",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "prometheus.metrics.storage_sof_total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "prometheus.metrics.storage_sof_used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total storage of each (TB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "dectbytes" }
   ],
   "targets": [
    {
     "alias": "Equallogic",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "prometheus.metrics.storage_el_total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "PFS",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "prometheus.metrics.storage_pfs_total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "SOF",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "prometheus.metrics.storage_sof_total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Consortium Provisions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "prometheus.labels.consortium",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "prometheus.metrics.storage_gws_provision",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PFS usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "dectbytes" }
   ],
   "targets": [
    {
     "alias": "Total",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "prometheus.metrics.storage_pfs_total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "Used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "prometheus.metrics.storage_pfs_used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}